name: ebox
description: Hills 风格 Emby 客户端
publish_to: 'none'
version: 5.0.8+50008

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  provider: ^6.1.1
  go_router: ^13.0.0
  http: ^1.1.0
  video_player: ^2.8.1
  path_provider: ^2.1.1
  cached_network_image: ^3.3.0
  audio_video_progress_bar: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
