name: Build Windows EXE

on:
  push:
    tags:
      - 'v*-win'
  workflow_dispatch:
    inputs:
      version:
        description: '版本号'
        required: true
        default: 'v5.0.8'

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 40
    
    steps:
      - uses: actions/checkout@v4
      
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.0'
          channel: 'stable'
      
      - name: Build Windows
        working-directory: ./client
        run: |
          flutter config --enable-windows-desktop
          flutter pub get
          flutter build windows --release --verbose
      
      - name: Upload Release
        uses: softprops/action-gh-release@v3
        with:
          name: E 宝盒 ${{ github.ref_name || github.event.inputs.version }}
          tag_name: ${{ github.ref_name || github.event.inputs.version }}
          body: |
            ## Windows 便携版
          files: ./client/build/windows/runner/Release/*.exe
          draft: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
